---

- name: Test play
  hosts: all
  gather_facts: no
  tasks:
    - name: Debug task
      debug:
        msg: Hello world!
      tags:
        - debug

    - name: Template task
      template:
        src: test.j2
        dest: /tmp/test.txt
      tags:
        - template
